### ISSUE TITLE
App crash with: java.lang.IllegalArgumentException: Receiver not registered: com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager$BluetoothHeadsetBroadcastReceiver@21990f5

### ISSUE THREAD

**Issue by elbow** [react-native-webrtc/react-native-incall-manager#130]
Saw this application crash within incallmanager.

Looking at the error it looks like a bluetooth device disappeared under us?

``` 
 java.lang.RuntimeException: Unable to destroy activity {com.xxxxx.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager$BluetoothHeadsetBroadcastReceiver@21990f5
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4652)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager$BluetoothHeadsetBroadcastReceiver@21990f5
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1219)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1518)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
	at com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager.unregisterReceiver(AppRTCBluetoothManager.java:396)
	at com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager.stop(AppRTCBluetoothManager.java:285)
	at com.zxcpoiu.incallmanager.InCallManagerModule.stop(InCallManagerModule.java:615)
	at com.zxcpoiu.incallmanager.InCallManagerModule.stop(InCallManagerModule.java:597)
	at com.zxcpoiu.incallmanager.InCallManagerModule.onHostDestroy(InCallManagerModule.java:1593)
	at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:237)
	at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:687)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:596)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:610)
	at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:117)
	at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:70)
	at android.app.Activity.performDestroy(Activity.java:7561)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1257)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
	... 9 more
 
 ```

**Comment by TorgeirCook** [comment]
This is also happening in randomly in our application and I'm having a hard time reproducing it. Do have any tips for reproducing this error @elbow ?

**Comment by ThumbstackTech** [comment]
@TorgeirCook @elbow any more info this?

**Comment by eduduardo** [comment]
I have the same crash here:
```
java.lang.RuntimeException: Unable to destroy activity {xxxx/xxxx.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.zxcpoiu.incallmanager.a.a$b@273d1cf
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4335)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4353)
        at android.app.ActivityThread.-wrap6(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6351)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)

Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.zxcpoiu.incallmanager.a.a$b@273d1cf
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1053)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1332)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
        at com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager.unregisterReceiver(AppRTCBluetoothManager.java:396)
        at com.zxcpoiu.incallmanager.AppRTC.AppRTCBluetoothManager.stop(AppRTCBluetoothManager.java:285)
        at com.zxcpoiu.incallmanager.InCallManagerModule.stop(InCallManagerModule.java:615)
        at com.zxcpoiu.incallmanager.InCallManagerModule.stop(InCallManagerModule.java:597)
        at com.zxcpoiu.incallmanager.InCallManagerModule.onHostDestroy(InCallManagerModule.java:1593)
        at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:282)
        at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:742)
        at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:636)
        at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:650)
        at com.facebook.react.ReactDelegate.onHostDestroy(ReactDelegate.java:73)
        at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:108)
        at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:63)
        at android.app.Activity.performDestroy(Activity.java:6977)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4322)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4353)
        at android.app.ActivityThread.-wrap6(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1607)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6351)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
```

**Comment by yasir-syed** [comment]
getting same crash on InCallManager.stop(); when Android device is in silent mode.
is there any fix? is there any way to stop the app crashing? try catch doesn't work either.
What would happen if InCallManager.stop() is not called in this particular scenario ?
